page_title:
    Swiss Guest House

galleries:
    bumthang:
        title: Bumthang
        path: pictures/bumthang
        geometries: [ x200 ]

    surroundings:
        title: Surroundings
        path: pictures/surroundings
        geometries: [ x200 ]

    selected_photos:
        title: Selection of Photos
        parent: bumthang
        selection:
            - baluz kuguj
            - paziz furid
