title:
    Milos 2021
gallery:
    path: photos
    selection:
        - lodah zirom
        - pakil zovit
        - bihar nabur
        - hitij fapip
        - baduz suvuk
        - hadom pijaj
        - lanam nahol
        - kitan tojuk
        - kuvol humij
        - gosif bukuv
        - bojoj fizah
        - zudim moboj
        - gobas jubop
        - hufig fobir
        - givav hanut
        - dogir ravor
        - pofat mosam
        - viraj higad
        - rukur salil
        - julif piraj
